import os
import json
import errno
import sys
sys.path.append(os.path.join(os.path.dirname(__file__), '..'))
import utils.utils as utils
import utils.config as config

mode = config.mode
temperature = config.temperature
models = config.models
runs = config.runs


def filter_out_of_bound_values(values):
    if mode == "success":
        return [v for v in values if 0 <= v and v <= 18446744073709551615]
    elif mode == "error_code":
        return [v for v in values if hasattr(errno, v)]


def get_llm_generated_values(data):
    if mode == "success":
        return data["test_values"]
    elif mode == "error_code":
        return data["error_codes"]
    

def set_llm_generated_values(data, values):
    if mode == "success":
        data["test_values"] = values
    elif mode == "error_code":
        data["error_codes"] = values


def process_json_file(file_path):
    with open(file_path, 'r') as file:
        data = json.load(file)

        # get the values generated by the LLM
        values = get_llm_generated_values(data)

        # filter out of bound values
        filtered_values = filter_out_of_bound_values(values)

        # if no values are left after filtering, skip writing the file
        if not filtered_values:
            return

        # replace the values in the data
        set_llm_generated_values(data, filtered_values)

        # output path
        output_path = file_path.replace("/json/", "/json_filtered/")
        os.makedirs(os.path.dirname(output_path), exist_ok=True)

        # write the modified data back to the file
        with open(output_path, 'w') as file:
            json.dump(data, file, indent=4)


def process_all_json(directory):
    for filename in os.listdir(directory):
        file_path = os.path.join(directory, filename)
        # only process valid JSON files
        if utils.is_json(file_path):
            process_json_file(file_path)


def process_all_runs(directory):
    for run in range(1, runs + 1):
        run_dir = os.path.join(directory, f"run{run}")
        if os.path.isdir(run_dir):
            process_all_json(run_dir)


def process_all_models(directory):
    for model in models:
        model_dir = os.path.join(directory, model)
        if os.path.isdir(model_dir):
            process_all_runs(model_dir)


def process_all_temperatures(directory):
    for temp in [f"temperature_{temp}" for temp in temperature]:
        temperature_dir = os.path.join(directory, temp)
        if os.path.isdir(temperature_dir):
            process_all_models(temperature_dir)