# Copyright (c) 2025 Robert Bosch GmbH
# SPDX-License-Identifier: AGPL-3.0

from pathlib import Path


def extract_syscalls_from_statistics(aut: str):
    root_dir = Path(__file__).resolve().parents[2]
    file_path = f"{root_dir}/syscallm-injection/examples/statistics/{aut}.oracle"

    with open(file_path, 'r') as f:
        next(f)
        next(f)
        for line in f:
            parts = line.strip().split()
            syscall = parts[-1]
            count = parts[3]

            if '-' in syscall:
                break
            yield syscall, int(count)


# TODO: Update
def get_memcached_syscalls():
    return {
        "accept4": 1,
        "access": 14,
        "arch_prctl": 5,
        "bind": 4,
        "brk": 16,
        "chdir": 1,
        "clock_nanosleep": 189,
        "clone": 13,
        "clone3": 9,
        "close": 76,
        "connect": 14,
        "dup": 1,
        "dup2": 4,
        "epoll_create1": 5,
        "epoll_ctl": 11,
        "epoll_wait": 79,
        "eventfd2": 8,
        "execve": 5,
        "exit_group": 2,
        "fcntl": 10,
        "futex": 156,
        "getcwd": 1,
        "getegid": 29,
        "geteuid": 29,
        "getgid": 29,
        "getpeername": 1,
        "getpgrp": 1,
        "getpid": 8,
        "getppid": 3,
        "getrandom": 5,
        "getsockname": 6,
        "getsockopt": 1,
        "getuid": 30,
        "ioctl": 6,
        "listen": 2,
        "lseek": 11,
        "mkdir": 2,
        "mmap": 119,
        "mprotect": 41,
        "munmap": 12,
        "newfstatat": 128,
        "openat": 104,
        "pipe2": 5,
        "poll": 4,
        "pread64": 10,
        "prlimit64": 10,
        "pselect6": 1,
        "read": 56,
        "recvmsg": 6,
        "rseq": 14,
        "rt_sigaction": 52,
        "rt_sigprocmask": 66,
        "rt_sigreturn": 2,
        "sendmsg": 1,
        "sendto": 2,
        "set_robust_list": 18,
        "set_tid_address": 5,
        "setgid": 1,
        "setgroups": 1,
        "setsockopt": 9,
        "setuid": 1,
        "socket": 16,
        "statfs": 2,
        "sysinfo": 1,
        "umask": 2,
        "uname": 1,
        "wait4": 4,
        "write": 13
    }

def get_nginx_syscalls():
    return {
        "accept4": 1,
        "access": 22,
        "arch_prctl": 8,
        "bind": 1,
        "brk": 49,
        "chdir": 1,
        "chown": 5,
        "clock_nanosleep": 1,
        "clone": 24,
        "close": 349,
        "connect": 9,
        "copy_file_range": 3,
        "dup2": 6,
        "epoll_create": 17,
        "epoll_ctl": 83,
        "epoll_wait": 137,
        "eventfd2": 32,
        "execve": 8,
        "exit_group": 8,
        "fadvise64": 3,
        "fcntl": 62,
        "futex": 41,
        "getcwd": 1,
        "getdents64": 2,
        "getegid": 11,
        "geteuid": 32,
        "getgid": 11,
        "getpeername": 2,
        "getpgrp": 1,
        "getpid": 34,
        "getppid": 4,
        "getrandom": 10,
        "getsockname": 3,
        "getsockopt": 1,
        "gettid": 22,
        "getuid": 11,
        "io_setup": 16,
        "ioctl": 80,
        "listen": 2,
        "lseek": 34,
        "mkdir": 7,
        "mmap": 319,
        "mprotect": 75,
        "munmap": 11,
        "newfstatat": 225,
        "openat": 178,
        "poll": 6,
        "prctl": 16,
        "pread64": 20,
        "prlimit64": 12,
        "pwrite64": 1,
        "read": 167,
        "recvfrom": 3,
        "recvmsg": 238,
        "rseq": 8,
        "rt_sigaction": 113,
        "rt_sigprocmask": 82,
        "rt_sigreturn": 6,
        "sendfile": 1,
        "sendmsg": 120,
        "sendto": 1,
        "set_robust_list": 32,
        "set_tid_address": 8,
        "setgid": 16,
        "setgroups": 16,
        "setsid": 1,
        "setsockopt": 6,
        "setuid": 16,
        "socket": 10,
        "socketpair": 33,
        "statfs": 8,
        "sysinfo": 3,
        "umask": 3,
        "uname": 3,
        "wait4": 13,
        "write": 29,
        "writev": 1
    }

def get_python_syscalls():
    return {
        "access": 9,
        "arch_prctl": 4,
        "brk": 27,
        "chdir": 1,
        "clone": 2,
        "close": 106,
        "close_range": 2,
        "connect": 2,
        "dup2": 4,
        "epoll_create1": 1,
        "execve": 9,
        "exit_group": 4,
        "fadvise64": 1,
        "fcntl": 10,
        "futex": 17,
        "getcwd": 2,
        "getdents64": 24,
        "getegid": 5,
        "geteuid": 5,
        "getgid": 5,
        "getpgrp": 1,
        "getpid": 6,
        "getppid": 3,
        "getrandom": 6,
        "gettid": 2,
        "getuid": 5,
        "ioctl": 52,
        "lseek": 92,
        "mkdir": 2,
        "mmap": 105,
        "mprotect": 25,
        "munmap": 8,
        "newfstatat": 455,
        "open": 1,
        "openat": 116,
        "pipe2": 2,
        "pread64": 8,
        "prlimit64": 6,
        "read": 121,
        "readlink": 9,
        "rseq": 4,
        "rt_sigaction": 159,
        "rt_sigprocmask": 24,
        "rt_sigreturn": 2,
        "set_robust_list": 6,
        "set_tid_address": 4,
        "socket": 2,
        "statfs": 2,
        "sysinfo": 1,
        "umask": 2,
        "uname": 1,
        "vfork": 1,
        "wait4": 5,
        "write": 4
    }

def get_redis_syscalls():
    return {
        "access": 9,
        "arch_prctl": 1,
        "brk": 3,
        "clone": 13,
        "close": 12,
        "connect": 2,
        "dup2": 3,
        "execve": 1,
        "fcntl": 8,
        "futex": 1,
        "getcwd": 1,
        "getegid": 9,
        "geteuid": 9,
        "getgid": 9,
        "getpgrp": 1,
        "getpid": 4,
        "getppid": 3,
        "getrandom": 1,
        "getuid": 9,
        "ioctl": 23,
        "lseek": 23,
        "mmap": 15,
        "mprotect": 4,
        "munmap": 1,
        "newfstatat": 43,
        "openat": 13,
        "pread64": 2,
        "prlimit64": 3,
        "read": 23,
        "rseq": 1,
        "rt_sigaction": 40,
        "rt_sigprocmask": 136,
        "rt_sigreturn": 12,
        "set_robust_list": 1,
        "set_tid_address": 1,
        "socket": 2,
        "sysinfo": 1,
        "uname": 1,
        "wait4": 25,
        "write": 1
    }

syscall_getters = {
    "redis": get_redis_syscalls,
    "python": get_python_syscalls,
    "memcached": get_memcached_syscalls,
    "nginx": get_nginx_syscalls
}

if __name__ == "__main__":
    aut = input("Enter application name (redis/python/memcached/nginx): ")

    syscall_count = extract_syscalls_from_statistics(aut)
    syscall_count = sorted(syscall_count, key=lambda x: x[0])

    for syscall, count in syscall_count:
        print(f'"{syscall}": {count},')